/**
 * Deterministic demo dataset for the Aura-Guard Compliance Auditor.
 * 10 AI decisions across two policy versions with a mix of statuses.
 *
 * The evidence block is intentionally left empty here — it is populated by
 * buildHashChain() on load so that a) the demo works offline, and
 * b) tampering is instantly detectable against the freshly derived hashes.
 */

export const REGISTERED_POLICY_VERSIONS = ["policy-2025.11-r1", "policy-2025.12-r2"];

export const SAMPLE_SESSION = {
    session_id: "AG-SESS-2026-02-01-01",
    session_name: "Q1-2026 AI Decision Audit",
    organization: "Meridian Financial Services",
    auditor: "Compliance Operations",
    generated_at: "2026-02-01T09:00:00Z",
    registered_policy_versions: REGISTERED_POLICY_VERSIONS,
    decisions: [
        {
            id: "DEC-0001",
            timestamp: "2026-01-27T08:12:04Z",
            model: "credit-scoring-v3.1",
            subject: "APP-88213",
            action: "credit_application_review",
            policy_version: "policy-2025.11-r1",
            policy_status: "compliant",
            reason: "Applicant profile within tier-2 risk envelope; all required disclosures present.",
            input: { income_bracket: "60k-90k", tenure_months: 42, region: "NA-EAST" },
            output: { decision: "approve", credit_limit: 12000, tier: "T2" },
        },
        {
            id: "DEC-0002",
            timestamp: "2026-01-27T08:14:22Z",
            model: "credit-scoring-v3.1",
            subject: "APP-88214",
            action: "credit_application_review",
            policy_version: "policy-2025.11-r1",
            policy_status: "warning",
            reason: "Manual review advised: debt-to-income ratio approaches threshold (0.41 vs 0.45 cap).",
            input: { income_bracket: "45k-60k", tenure_months: 11, region: "NA-WEST" },
            output: { decision: "manual_review", credit_limit: null, tier: "T3" },
        },
        {
            id: "DEC-0003",
            timestamp: "2026-01-27T08:19:47Z",
            model: "kyc-screening-v2.4",
            subject: "APP-88215",
            action: "identity_verification",
            policy_version: "policy-2025.11-r1",
            policy_status: "violation",
            reason: "Sanction-list watchword matched without documented override rationale.",
            input: { document_type: "passport", country: "XX", risk_flags: ["watchlist"] },
            output: { decision: "reject", escalation: "compliance_officer" },
        },
        {
            id: "DEC-0004",
            timestamp: "2026-01-27T08:23:11Z",
            model: "fraud-detection-v1.8",
            subject: "TXN-4521-9910",
            action: "transaction_scoring",
            policy_version: "policy-2025.11-r1",
            policy_status: "compliant",
            reason: "Transaction pattern consistent with cardholder baseline; risk score below 0.30.",
            input: { amount: 128.4, currency: "USD", merchant_category: "grocery" },
            output: { decision: "allow", risk_score: 0.11 },
        },
        {
            id: "DEC-0005",
            timestamp: "2026-01-27T08:31:52Z",
            model: "fraud-detection-v1.8",
            subject: "TXN-4521-9917",
            action: "transaction_scoring",
            policy_version: "policy-2025.11-r1",
            policy_status: "warning",
            reason: "Elevated velocity across three merchants within 12 minutes; step-up authentication recommended.",
            input: { amount: 640.0, currency: "USD", merchant_category: "electronics" },
            output: { decision: "step_up_auth", risk_score: 0.62 },
        },
        {
            id: "DEC-0006",
            timestamp: "2026-01-27T09:02:19Z",
            model: "credit-scoring-v3.2",
            subject: "APP-88221",
            action: "credit_application_review",
            policy_version: "policy-2025.12-r2",
            policy_status: "compliant",
            reason: "New policy revision applied; adverse-action notice generated in required window.",
            input: { income_bracket: "90k-120k", tenure_months: 67, region: "EU-CENTRAL" },
            output: { decision: "approve", credit_limit: 25000, tier: "T1" },
        },
        {
            id: "DEC-0007",
            timestamp: "2026-01-27T09:08:44Z",
            model: "kyc-screening-v2.5",
            subject: "APP-88222",
            action: "identity_verification",
            policy_version: "policy-2025.12-r2",
            policy_status: "compliant",
            reason: "All KYC evidence collected; PEP screen clear; document freshness within 30 days.",
            input: { document_type: "driver_license", country: "DE", risk_flags: [] },
            output: { decision: "verified" },
        },
        {
            id: "DEC-0008",
            timestamp: "2026-01-27T09:15:03Z",
            model: "fraud-detection-v1.9",
            subject: "TXN-4522-0114",
            action: "transaction_scoring",
            policy_version: "policy-2025.12-r2",
            policy_status: "violation",
            reason: "Cross-border pattern flagged by rule R-CBX-12 without required compensating evidence.",
            input: { amount: 8900.0, currency: "USD", merchant_category: "wire_transfer" },
            output: { decision: "block", risk_score: 0.94 },
        },
        {
            id: "DEC-0009",
            timestamp: "2026-01-27T09:22:37Z",
            model: "credit-scoring-v3.2",
            subject: "APP-88223",
            action: "credit_application_review",
            policy_version: "policy-2025.12-r2",
            policy_status: "warning",
            reason: "Thin credit file; supplementary income evidence flagged for reviewer confirmation.",
            input: { income_bracket: "30k-45k", tenure_months: 4, region: "NA-EAST" },
            output: { decision: "manual_review", credit_limit: null, tier: "T4" },
        },
        {
            id: "DEC-0010",
            timestamp: "2026-01-27T09:31:08Z",
            model: "fraud-detection-v1.9",
            subject: "TXN-4522-0141",
            action: "transaction_scoring",
            policy_version: "policy-2025.12-r2",
            policy_status: "compliant",
            reason: "Recurring merchant, amount within 10% of 30-day baseline; risk score below 0.20.",
            input: { amount: 42.99, currency: "USD", merchant_category: "subscription" },
            output: { decision: "allow", risk_score: 0.08 },
        },
    ],
};
